CREATE TYPE "public"."media_status" AS ENUM('pending', 'processing', 'completed', 'failed');--> statement-breakpoint
CREATE TYPE "public"."media_type" AS ENUM('image', 'video', 'audio');--> statement-breakpoint
CREATE TABLE "rethink-media_chat" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "rethink-media_chat_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(256),
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "rethink-media_media" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "rethink-media_media_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"chatId" integer NOT NULL,
	"media_type" "media_type" NOT NULL,
	"index" integer NOT NULL,
	"url" varchar(512) NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone,
	"media_status" "media_status" DEFAULT 'pending' NOT NULL
);
--> statement-breakpoint
ALTER TABLE "rethink-media_media" ADD CONSTRAINT "rethink-media_media_chatId_rethink-media_chat_id_fk" FOREIGN KEY ("chatId") REFERENCES "public"."rethink-media_chat"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "name_idx" ON "rethink-media_chat" USING btree ("name");--> statement-breakpoint
CREATE INDEX "media_chat_type_index_idx" ON "rethink-media_media" USING btree ("chatId","media_type","index");